### PR TITLE
Doc4

### PR DESCRIPTION
**Pull request by RerEngineer**
fixing the examples lnk.

### CODE REVIEW

**Comment by takev** [comment]
Hi, thank you for the pull request, I didn't notice the example was renamed.

It was actually meant to point at: https://github.com/hikogui/hikogui-hello-world/blob/main/src/main.cpp

This one has a lot more comments in the example.

**Comment by takev** [comment]
Thank you, it'll be merged soonish.

**Comment by RerEngineer** [comment]
make sure you also fix the svg https://github.com/hikogui/hikogui-hello-world/actions/workflows/build-on-windows.yml/badge.svg on the https://github.com/hikogui/hikogui-hello-world readme 👍🏼 .

**Comment by RerEngineer** [comment]
fixed https://github.com/hikogui/hikogui-hello-world/pull/41

**Pull request merged**
