### PR TITLE
fix generate_cmakelists

### PR DESCRIPTION
**Pull request by jakoch**
This enhances `generate_cmakelists.sh` to find python3 on multiple paths.
This fixes `generate_cmakelists.py` to avoid duplicate entries of "win32" files and include "macos" files.
 
Referencing the double inclusion errors in current CMakeList_Includes.txt file, e.g.

  - https://github.com/hikogui/hikogui/blob/main/CMakeLists_includes.cmake#L26-L36
  - https://github.com/hikogui/hikogui/blob/main/CMakeLists_includes.cmake#L90-L91
  
Referencing not properly handled files, because detection string is in middle of filename or part of path, e.g.

 - https://github.com/hikogui/hikogui/blob/main/CMakeLists_includes.cmake#L549-L550
 - https://github.com/hikogui/hikogui/blob/main/CMakeLists_includes.cmake#L553-L568
 
Additional notes:
-  I did not include the re-generated CMakeLists_includes.cmake file in the PR.
-  Python3 is now a build dependency (because generator for CMakeLists). This needs to be mentioned in docs/dependencies.md.

### CODE REVIEW

**Comment by jakoch** [comment]
This error is also present in the main branch.
https://github.com/hikogui/hikogui/actions/runs/9800085030/job/27291223425#step:10:133

**Comment by takev** [comment]
Yea, it looks like the build system (compiler/library) changed and something is not compiling anymore.
I will make a pull request to fix it.

**Comment by takev** [comment]
After downloading the new compiler, still builds on my system, grmbl.

**Comment by jakoch** [comment]
Yes, the error is not reproducible with MSVC 17.11.0 Preview 3, which "only" ships clang-cl v17.0.3.
On CI the error is from LLVM/Clang v18.1.6.
The issue is reproducible with latest [LLVM/Clang v18.1.8](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-pc-windows-msvc.tar.xz) (Warning: 1GB download, extracted 4,5GB).


Referencing the fix from the other PR: https://github.com/hikogui/hikogui/pull/701/commits/d5c24d43020f41d57bf33734363bdca72fb71198
      - observer_intf: Transfer ownership first, then call notify on the observer? Not sure if that's correct though. 
      - toggle_widget: And i've simply commented out the attributes stuff. That's gone in the other "set-style-branch" branch anyway.

**Pull request merged**
